# Generated by Django 4.0.4 on 2023-06-16 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='description',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
