# Generated by Django 4.0.4 on 2023-06-21 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0003_malumot_saqlash'),
    ]

    operations = [
        migrations.RenameField(
            model_name='malumot_saqlash',
            old_name='description',
            new_name='message',
        ),
    ]
